from __future__ import annotations

from las_editor.reservoir_property_calculator import (
    RESERVOIR_PROPERTY_CALCULATOR_SCHEMA,
    RESERVOIR_PROPERTY_CALCULATOR_STORAGE_KEY,
    ReservoirPropertyInputCurves,
    ReservoirPropertyParameters,
    ReservoirPropertyPlan,
    ReservoirPropertyIssue,
    ReservoirVolumeIntervalSummary,
    ReservoirPropertyResult,
    build_reservoir_property_manifest,
    calculate_bulk_rock_volume,
    calculate_pore_volumes,
    calculate_sample_thickness,
    filter_reservoir_depth_window,
    render_reservoir_property_markdown_report,
    reservoir_property_issue_table_rows,
    reservoir_volume_table_rows,
    run_reservoir_property_calculator,
    summarize_reservoir_volume_intervals,
    validate_reservoir_property_plan,
)



from las_editor.petrophysical_crossplot_workspace import (
    PETROPHYSICAL_CROSSPLOT_SCHEMA,
    PETROPHYSICAL_CROSSPLOT_STORAGE_KEY,
    CrossplotInputCurves,
    CrossplotPlan,
    CrossplotIssue,
    CrossplotTrend,
    CrossplotClusterSummary,
    CrossplotSpec,
    PetrophysicalCrossplotResult,
    build_crossplot_spec,
    build_petrophysical_crossplot_manifest,
    calculate_linear_trend,
    crossplot_cluster_table_rows,
    crossplot_issue_table_rows,
    crossplot_spec_table_rows,
    filter_crossplot_depth_window,
    render_petrophysical_crossplot_markdown_report,
    run_petrophysical_crossplot_workspace,
    summarize_crossplot_clusters,
    validate_crossplot_plan,
)




from las_editor.advanced_saturation_models import (
    ADVANCED_SATURATION_SCHEMA,
    ADVANCED_SATURATION_STORAGE_KEY,
    AdvancedSaturationPlan,
    AdvancedSaturationResult,
    DualWaterParameters,
    SaturationInputCurves,
    SaturationModelComparison,
    SaturationModelIssue,
    ShalySandParameters,
    build_advanced_saturation_manifest,
    calculate_dual_water_saturation,
    calculate_indonesia_water_saturation,
    calculate_simandoux_water_saturation,
    compare_saturation_models,
    recommend_saturation_model,
    render_advanced_saturation_markdown_report,
    run_advanced_saturation_models,
    saturation_comparison_table_rows,
    saturation_issue_table_rows,
    validate_advanced_saturation_plan,
)

from las_editor.petrophysical_workspace import (
    PETROPHYSICAL_WORKSPACE_SCHEMA,
    PETROPHYSICAL_WORKSPACE_STORAGE_KEY,
    ArchieParameters,
    PetrophysicalCutoffSet,
    PetrophysicalInputCurves,
    PetrophysicalIntervalSummary,
    PetrophysicalIssue,
    PetrophysicalPlan,
    PetrophysicalResult,
    ShaleVolumeParameters,
    build_petrophysical_manifest,
    calculate_archie_water_saturation,
    calculate_effective_porosity,
    calculate_net_pay_flags,
    calculate_shale_volume,
    petrophysical_interval_table_rows,
    petrophysical_issue_table_rows,
    render_petrophysical_markdown_report,
    run_petrophysical_workspace,
    summarize_petrophysical_intervals,
    validate_petrophysical_plan,
)




from las_editor.well_interval_manager import (
    WELL_INTERVAL_MANAGER_SCHEMA,
    WELL_INTERVAL_MANAGER_STORAGE_KEY,
    HYDROCARBON_TOKENS,
    RESERVOIR_FLAGS,
    IntervalCutoffSet,
    WellInterval,
    WellIntervalIssue,
    WellIntervalSet,
    build_well_interval_manifest,
    build_well_intervals_from_summary,
    calculate_interval_thickness_summary,
    classify_interval,
    merge_adjacent_intervals,
    render_well_interval_markdown_report,
    split_well_interval,
    well_interval_issue_table_rows,
    well_interval_table_rows,
)

from las_editor.formation_evaluation_summary import (
    FORMATION_EVALUATION_SCHEMA,
    FORMATION_EVALUATION_STORAGE_KEY,
    FormationEvaluationInterval,
    FormationEvaluationIssue,
    FormationEvaluationSummary,
    build_formation_evaluation_manifest,
    build_formation_evaluation_summary,
    formation_evaluation_interval_table_rows,
    formation_evaluation_issue_table_rows,
    render_formation_evaluation_markdown_report,
)





from las_editor.mud_gas_interpretation import (
    MUD_GAS_INTERPRETATION_SCHEMA,
    MUD_GAS_INTERPRETATION_STORAGE_KEY,
    MudGasIntervalSummary,
    MudGasInterpretationResult,
    MudGasInterpretationRow,
    MudGasIssue,
    MudGasRatioSet,
    build_mud_gas_interpretation_manifest,
    build_mud_gas_source_columns,
    calculate_mud_gas_ratios,
    classify_haworth,
    classify_oil_indicator,
    classify_pixler,
    interpret_mud_gas_dataframe,
    interpret_mud_gas_ratios,
    mud_gas_interval_table_rows,
    mud_gas_interpretation_table_rows,
    mud_gas_issue_table_rows,
    render_mud_gas_markdown_report,
    summarize_mud_gas_intervals,
)

from las_editor.las_processing_pipeline import (
    LAS_PROCESSING_PIPELINE_SCHEMA,
    LAS_PROCESSING_PIPELINE_STORAGE_KEY,
    SUPPORTED_PROCESSING_OPERATIONS,
    LasProcessingHistoryEntry,
    LasProcessingIssue,
    LasProcessingOperation,
    LasProcessingPlan,
    LasProcessingResult,
    apply_processing_operation,
    apply_processing_pipeline,
    build_processing_manifest,
    build_processing_plan,
    operation_table_rows,
    preview_processing_pipeline,
    processing_issue_table_rows,
    render_processing_report,
)

from las_editor.las_quality_control import (
    LAS_QUALITY_CONTROL_SCHEMA,
    LAS_QUALITY_CONTROL_STORAGE_KEY,
    CurveQualityProfile,
    LasQualityIssue,
    LasQualityReport,
    build_quality_control_manifest,
    builtin_quality_profiles,
    detect_depth_quality_issues,
    detect_flat_lines,
    detect_null_issues,
    detect_outliers,
    detect_range_issues,
    detect_spikes,
    detect_unit_mismatch,
    get_quality_profile,
    quality_issue_table_rows,
    quality_profile_table_rows,
    render_quality_control_report,
    run_las_quality_control,
)

from las_editor.curve_calculator import (
    CURVE_CALCULATOR_SCHEMA,
    CURVE_CALCULATOR_STORAGE_KEY,
    CurveCalculationHistoryEntry,
    CurveCalculationIssue,
    CurveCalculationPlan,
    CurveCalculationResult,
    CurveFormulaTemplate,
    apply_curve_calculation,
    build_curve_calculation_manifest,
    build_curve_calculation_plan,
    build_curve_calculation_plan_from_template,
    builtin_curve_formula_templates,
    calculate_curve_values,
    calculated_curve_spec,
    curve_calculation_issue_table_rows,
    curve_calculation_template_table_rows,
    get_curve_formula_template,
    preview_curve_calculation,
)



from las_editor.curve_importer import (
    CURVE_IMPORT_STORAGE_KEY,
    SUPPORTED_CONFLICT_POLICIES,
    SUPPORTED_MATCH_POLICIES,
    CurveImportHistoryEntry,
    CurveImportIssue,
    CurveImportPlan,
    CurveImportResult,
    build_curve_import_manifest,
    build_curve_import_plan,
    curve_import_issue_table_rows,
    curve_import_table_rows,
    import_curve_specs_from_table,
    merge_imported_curves,
    normalize_curve_import_table,
    read_curve_import_csv,
    read_curve_import_xlsx,
)




from las_editor.las_safe_export import (
    LAS_EXPORT_SCHEMA,
    LAS_SAFE_EXPORT_STORAGE_KEY,
    LAS_TEMPLATE_STORAGE_KEY,
    LasExportIssue,
    LasSafeExportManifest,
    LasTemplateProfile,
    builtin_las_template_profiles,
    build_las_export_manifest,
    create_las_spec_from_template,
    export_issue_table_rows,
    export_las_document_safely,
    export_las_text_safely,
    export_manifest_table,
    get_las_template_profile,
    las_template_table_rows,
    validate_safe_export_request,
)

from las_editor.las_validator import (
    LAS_VALIDATOR_STORAGE_KEY,
    DEFAULT_RANGE_RULES,
    LASValidator,
    LasValidationFinding,
    LasValidationReport,
    LasValidatorCenterResult,
    LasValidatorConfig,
    build_validation_summary,
    detect_las_sections,
    recommended_validator_actions,
    render_validation_report,
    validate_curve_ascii_alignment,
    validate_numeric_ranges,
    validate_las_ascii,
    validate_las_header,
    validate_las_sections,
    validate_las_workspace,
    validation_table_rows,
)


from las_editor.ascii_data_editor import (
    ASCII_EDITOR_STORAGE_KEY,
    DEFAULT_DEPTH_MNEMONICS,
    AsciiEditorHistoryEntry,
    AsciiEditorIssue,
    AsciiEditorResult,
    ascii_editor_summary,
    build_ascii_table,
    delete_ascii_rows,
    edit_ascii_cell,
    edit_ascii_range,
    find_depth_column,
    find_replace_ascii_values,
    insert_ascii_rows,
    normalize_ascii_dataframe,
    preview_ascii_changes,
    render_ascii_section,
    sort_ascii_by_depth,
    validate_ascii_data,
)

from las_editor.curve_manager import (
    CURVE_MANAGER_STORAGE_KEY,
    PROTECTED_DEPTH_CURVES,
    CurveManagerHistoryEntry,
    CurveManagerResult,
    add_curve_managed,
    build_curve_manifest,
    curve_manager_table_rows,
    delete_curve_managed,
    is_depth_curve,
    normalize_curve_manager_metadata,
    reorder_curves,
    update_curve_manifest_entry,
)

from las_editor.curve_grouping import (
    CurveGroupingHistoryEntry,
    CurveGroupingResult,
    assign_curve_group,
    available_curve_groups,
    build_curve_groups,
    curve_group_label,
    curve_group_table_rows,
    normalize_curve_group,
    suggest_curve_group,
    suggest_curve_groups,
    undo_last_group_assignment,
)

from las_editor.las_creator import (
    DEFAULT_NULL_VALUE,
    LAS_MANDATORY_SECTIONS,
    LasCreationResult,
    LasCreationSpec,
    LasCurveSpec,
    LasValidationIssue,
    add_las_curve,
    build_las_creation_spec,
    build_las_text,
    builtin_las_templates,
    create_las_dataframe,
    create_las_document,
    delete_las_curve,
    get_las_template_curves,
    normalize_las_mnemonic,
    normalize_las_unit,
    validate_las_creation,
)

from las_editor.depth_grid import (
    DepthDiagnostics,
    DepthDirectionFixResult,
    DepthGap,
    DepthStepOutlier,
    DepthStepReport,
    LasResampleResult,
    ManualDepthRowsResult,
    build_depth_grid,
    build_depth_step_report,
    diagnose_depths,
    fix_depth_direction,
    insert_manual_depth_rows,
    resample_las_data,
)

__all__ = [
    "ADVANCED_SATURATION_SCHEMA",
    "ADVANCED_SATURATION_STORAGE_KEY",
    "AdvancedSaturationPlan",
    "AdvancedSaturationResult",
    "DualWaterParameters",
    "SaturationInputCurves",
    "SaturationModelComparison",
    "SaturationModelIssue",
    "ShalySandParameters",
    "build_advanced_saturation_manifest",
    "calculate_dual_water_saturation",
    "calculate_indonesia_water_saturation",
    "calculate_simandoux_water_saturation",
    "compare_saturation_models",
    "recommend_saturation_model",
    "render_advanced_saturation_markdown_report",
    "run_advanced_saturation_models",
    "saturation_comparison_table_rows",
    "saturation_issue_table_rows",
    "validate_advanced_saturation_plan",
    "WELL_INTERVAL_MANAGER_SCHEMA",
    "WELL_INTERVAL_MANAGER_STORAGE_KEY",
    "HYDROCARBON_TOKENS",
    "RESERVOIR_FLAGS",
    "IntervalCutoffSet",
    "WellInterval",
    "WellIntervalIssue",
    "WellIntervalSet",
    "build_well_interval_manifest",
    "build_well_intervals_from_summary",
    "calculate_interval_thickness_summary",
    "classify_interval",
    "merge_adjacent_intervals",
    "render_well_interval_markdown_report",
    "split_well_interval",
    "well_interval_issue_table_rows",
    "well_interval_table_rows",
    "MUD_GAS_INTERPRETATION_SCHEMA",
    "MUD_GAS_INTERPRETATION_STORAGE_KEY",
    "MudGasIntervalSummary",
    "MudGasInterpretationResult",
    "MudGasInterpretationRow",
    "MudGasIssue",
    "MudGasRatioSet",
    "build_mud_gas_interpretation_manifest",
    "build_mud_gas_source_columns",
    "calculate_mud_gas_ratios",
    "classify_haworth",
    "classify_oil_indicator",
    "classify_pixler",
    "interpret_mud_gas_dataframe",
    "interpret_mud_gas_ratios",
    "mud_gas_interval_table_rows",
    "mud_gas_interpretation_table_rows",
    "mud_gas_issue_table_rows",
    "render_mud_gas_markdown_report",
    "summarize_mud_gas_intervals",
    "LAS_PROCESSING_PIPELINE_SCHEMA",
    "LAS_PROCESSING_PIPELINE_STORAGE_KEY",
    "SUPPORTED_PROCESSING_OPERATIONS",
    "LasProcessingHistoryEntry",
    "LasProcessingIssue",
    "LasProcessingOperation",
    "LasProcessingPlan",
    "LasProcessingResult",
    "apply_processing_operation",
    "apply_processing_pipeline",
    "build_processing_manifest",
    "build_processing_plan",
    "operation_table_rows",
    "preview_processing_pipeline",
    "processing_issue_table_rows",
    "render_processing_report",
    "preview_curve_calculation",
    "get_curve_formula_template",
    "curve_calculation_template_table_rows",
    "curve_calculation_issue_table_rows",
    "calculated_curve_spec",
    "calculate_curve_values",
    "builtin_curve_formula_templates",
    "build_curve_calculation_plan_from_template",
    "build_curve_calculation_plan",
    "build_curve_calculation_manifest",
    "apply_curve_calculation",
    "CurveFormulaTemplate",
    "CurveCalculationResult",
    "CurveCalculationPlan",
    "CurveCalculationIssue",
    "CurveCalculationHistoryEntry",
    "CURVE_CALCULATOR_STORAGE_KEY",
    "CURVE_CALCULATOR_SCHEMA",
    "CURVE_IMPORT_STORAGE_KEY",
    "SUPPORTED_CONFLICT_POLICIES",
    "SUPPORTED_MATCH_POLICIES",
    "CurveImportHistoryEntry",
    "CurveImportIssue",
    "CurveImportPlan",
    "CurveImportResult",
    "build_curve_import_manifest",
    "build_curve_import_plan",
    "curve_import_issue_table_rows",
    "curve_import_table_rows",
    "import_curve_specs_from_table",
    "merge_imported_curves",
    "normalize_curve_import_table",
    "read_curve_import_csv",
    "read_curve_import_xlsx",

    "validate_safe_export_request",
    "las_template_table_rows",
    "get_las_template_profile",
    "export_manifest_table",
    "export_las_text_safely",
    "export_las_document_safely",
    "export_issue_table_rows",
    "create_las_spec_from_template",
    "build_las_export_manifest",
    "builtin_las_template_profiles",
    "LasTemplateProfile",
    "LasSafeExportManifest",
    "LasExportIssue",
    "LAS_TEMPLATE_STORAGE_KEY",
    "LAS_SAFE_EXPORT_STORAGE_KEY",
    "LAS_EXPORT_SCHEMA",

    "validation_table_rows",
    "validate_las_workspace",
    "validate_las_sections",
    "validate_las_header",
    "validate_las_ascii",
    "validate_curve_ascii_alignment",
    "render_validation_report",
    "detect_las_sections",
    "build_validation_summary",
    "LasValidationReport",
    "LasValidationFinding",
    "LAS_VALIDATOR_STORAGE_KEY",
    "validate_ascii_data",
    "sort_ascii_by_depth",
    "render_ascii_section",
    "preview_ascii_changes",
    "normalize_ascii_dataframe",
    "insert_ascii_rows",
    "find_replace_ascii_values",
    "find_depth_column",
    "edit_ascii_range",
    "edit_ascii_cell",
    "delete_ascii_rows",
    "build_ascii_table",
    "ascii_editor_summary",
    "AsciiEditorResult",
    "AsciiEditorIssue",
    "AsciiEditorHistoryEntry",
    "DEFAULT_DEPTH_MNEMONICS",
    "ASCII_EDITOR_STORAGE_KEY",
    "update_curve_manifest_entry",
    "reorder_curves",
    "normalize_curve_manager_metadata",
    "is_depth_curve",
    "delete_curve_managed",
    "curve_manager_table_rows",
    "build_curve_manifest",
    "add_curve_managed",
    "CurveManagerResult",
    "CurveManagerHistoryEntry",
    "PROTECTED_DEPTH_CURVES",
    "CURVE_MANAGER_STORAGE_KEY",
    "validate_las_creation",
    "normalize_las_unit",
    "normalize_las_mnemonic",
    "get_las_template_curves",
    "delete_las_curve",
    "create_las_document",
    "create_las_dataframe",
    "builtin_las_templates",
    "build_las_text",
    "build_las_creation_spec",
    "add_las_curve",
    "LasValidationIssue",
    "LasCurveSpec",
    "LasCreationSpec",
    "LasCreationResult",
    "LAS_MANDATORY_SECTIONS",
    "DEFAULT_NULL_VALUE",
    "CurveGroupingHistoryEntry",
    "CurveGroupingResult",
    "assign_curve_group",
    "available_curve_groups",
    "build_curve_groups",
    "curve_group_label",
    "curve_group_table_rows",
    "normalize_curve_group",
    "suggest_curve_group",
    "suggest_curve_groups",
    "undo_last_group_assignment",
    "DepthDiagnostics",
    "DepthDirectionFixResult",
    "DepthGap",
    "DepthStepOutlier",
    "DepthStepReport",
    "LasResampleResult",
    "ManualDepthRowsResult",
    "build_depth_grid",
    "build_depth_step_report",
    "diagnose_depths",
    "fix_depth_direction",
    "insert_manual_depth_rows",
    "resample_las_data",
]

# Phase II B.4: LAS ASCII Data Editor Professional helpers are available from las_editor.ascii_data_editor.

from las_editor.petrophysical_report_package import (
    PETROPHYSICAL_REPORT_PACKAGE_SCHEMA,
    PETROPHYSICAL_REPORT_PACKAGE_STORAGE_KEY,
    PetrophysicalReportPackage,
    ReportPackageIssue,
    ReportPackageSection,
    build_crossplot_section,
    build_intervals_section,
    build_petrophysical_report_manifest,
    build_petrophysical_report_package,
    build_petrophysical_section,
    build_saturation_section,
    build_volumes_section,
    render_petrophysical_report_markdown,
    report_issue_table_rows,
    report_section_table_rows,
    validate_report_package,
)

from las_editor.las_merge_append_center import (
    LAS_MERGE_APPEND_SCHEMA,
    LAS_MERGE_APPEND_STORAGE_KEY,
    LasMergeAppendHistoryEntry,
    LasMergeAppendIssue,
    LasMergeAppendResult,
    append_las_depth_intervals,
    build_las_merge_append_manifest,
    insert_las_curves_from_las,
)
